/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { Footer, Header } from '../SiteChrome';

export const metadata = { title: 'Espaço na Mesa | Café com Mattoso', description: 'Pessoas, conversas e ideias que ajudam a construir o Café com Mattoso.' };

type PersonProps = { name: string; fullName: string; image: string; linkedIn: string; children: React.ReactNode; reverse?: boolean };
function PersonAtTheTable({ name, fullName, image, linkedIn, children, reverse }: PersonProps) { return <article className={`person-at-table ${reverse ? 'person-reverse' : ''}`}><div className="person-image"><img src={image} alt={`Retrato de ${fullName}`} /></div><div className="person-copy"><p className="eyebrow">À mesa</p><h2>{name}</h2><small>{fullName}</small><p>{children}</p><a className="text-link" href={linkedIn} target="_blank" rel="noreferrer">LinkedIn do {name} <b>→</b></a></div></article>; }

export default function NaMesa() { return <main><Header /><section className="page-hero wrap table-hero"><p className="eyebrow">Café com Mattoso</p><h1>Espaço na Mesa</h1><h2>Essa mesa sempre teve mais cadeiras.</h2><p>O Café com Mattoso nasceu de histórias, ideias, erros, conversas, projetos e decisões. Mas nenhuma dessas coisas acontece sozinha. Algumas pessoas atravessam a caminhada e deixam parte delas no que construímos.</p></section><section className="wrap section table-intro"><p className="eyebrow">O que é</p><h2>Não é uma lista de parceiros.<br />É um lugar para reconhecer presença.</h2><p>Pessoas que ajudaram a construir ideias, atravessar fases, questionar certezas ou simplesmente permaneceram por perto quando isso fez diferença.</p><strong>Colocar pessoas em primeiro lugar também significa reconhecer quem sentou à mesa conosco.</strong></section><section className="wrap section mesacast"><div><p className="eyebrow">Em construção</p><h2>MesaCast<br />com Mattoso</h2></div><div><p>Uma extensão do Café para trazer mais cadeiras à mesa. Não para procurar respostas definitivas, mas para ouvir pessoas reais falando sobre escolhas, trabalho, vida, tecnologia, histórias e os caminhos que precisaram atravessar.</p><blockquote>“Nem toda conversa precisa terminar com uma resposta. Às vezes basta alguém colocar outra cadeira na mesa.”</blockquote></div></section><section className="wrap people-section"><PersonAtTheTable name="Felipe" fullName="Felipe Ralph" image="/images/na-mesa/felipe.png" linkedIn="https://www.linkedin.com/in/feliperalph/">Algumas pessoas entram nos projetos pelas ideias. Outras entram pelas conversas. Algumas acabam ficando nas duas coisas. Este espaço será usado para contar por que Felipe faz parte dessa mesa.</PersonAtTheTable><PersonAtTheTable name="Will" fullName="Willyan Pereira" image="/images/na-mesa/will.png" linkedIn="https://www.linkedin.com/in/willyanpereira/" reverse>Tem gente que ajuda resolvendo. Tem gente que ajuda ficando. Algumas pessoas fazem os dois. Este espaço será usado para contar por que Will faz parte dessa mesa.</PersonAtTheTable></section><section className="wrap section empty-chairs"><p className="eyebrow">Ainda há espaço</p><h2>Ainda existem cadeiras vazias.</h2><p>O Espaço na Mesa não precisa terminar nessas duas histórias. Outras pessoas, conversas e encontros podem chegar aqui com o tempo. Algumas pela amizade. Algumas pelo trabalho. Algumas por uma história que ainda nem começou.</p><strong>Essa mesa sempre teve mais cadeiras.</strong><br /><Link className="button primary" href="/">Voltar para o Café</Link></section><Footer /></main>; }
