/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { Footer, Header } from '../SiteChrome';
import { publicAsset } from '../public-asset';
import { pageMetadata } from '../seo';

export const metadata = pageMetadata({ title: 'Espaço na Mesa', description: 'Pessoas, conversas e ideias que ajudam a construir o Café com Mattoso.', path: '/na-mesa' });

type PersonProps = { name: string; fullName: string; image: string; linkedIn: string; children: React.ReactNode; reverse?: boolean };
function PersonAtTheTable({ name, fullName, image, linkedIn, children, reverse }: PersonProps) { return <article className={`person-at-table ${reverse ? 'person-reverse' : ''}`}><div className="person-image"><img src={image} alt={`Retrato de ${fullName}`} /></div><div className="person-copy"><p className="eyebrow">À mesa</p><h2>{name}</h2><small>{fullName}</small><p>{children}</p><a className="text-link" href={linkedIn} target="_blank" rel="noreferrer">LinkedIn do {name} <b>→</b></a></div></article>; }

export default function NaMesa() { return <main id="main-content" className="theme--cafe"><Header /><section className="page-hero wrap table-hero"><p className="eyebrow">Café com Mattoso</p><h1>Espaço na Mesa</h1><h2>Essa mesa sempre teve mais cadeiras.</h2><p>O Café com Mattoso nasceu de histórias, ideias, erros, conversas, projetos e decisões. Mas nenhuma dessas coisas acontece sozinha. Algumas pessoas atravessam a caminhada e deixam parte delas no que construímos.</p></section><section className="wrap section table-intro"><p className="eyebrow">O que é</p><h2>Não é uma lista de parceiros.<br />É um lugar para reconhecer presença.</h2><p>Pessoas que ajudaram a construir ideias, atravessar fases, questionar certezas ou simplesmente permaneceram por perto quando isso fez diferença.</p><strong>Colocar pessoas em primeiro lugar também significa reconhecer quem sentou à mesa conosco.</strong></section><section className="wrap people-section"><PersonAtTheTable name="Felipe" fullName="Felipe Ralph" image={publicAsset('images/na-mesa/felipe.png')} linkedIn="https://www.linkedin.com/in/feliperalph/">Algumas pessoas entram nos projetos pelas ideias. Outras entram pelas conversas. Algumas acabam ficando nas duas coisas. Felipe faz parte dessa mesa pelas duas razões.</PersonAtTheTable><PersonAtTheTable name="Will" fullName="Willyan Pereira" image={publicAsset('images/na-mesa/will.png')} linkedIn="https://www.linkedin.com/in/willyanpereira/" reverse>Tem gente que ajuda resolvendo. Tem gente que ajuda ficando. Algumas pessoas fazem os dois. Will é uma dessas presenças na caminhada.</PersonAtTheTable></section><section className="wrap section empty-chairs"><p className="eyebrow">Ainda há espaço</p><h2>Ainda existem cadeiras vazias.</h2><p>O Espaço na Mesa não precisa terminar nessas duas histórias. Outras pessoas, conversas e encontros podem chegar aqui com o tempo. Algumas pela amizade. Algumas pelo trabalho. Algumas por uma história que ainda nem começou.</p><strong>Essa mesa sempre teve mais cadeiras.</strong><br /><Link className="button primary" href="/">Voltar para o Café</Link></section><Footer /></main>; }
