import { publicAsset } from './public-asset';

export const projectCategories = ['Tecnologia', 'Conteúdo', 'Entretenimento'] as const;
export const projectStatuses = ['Ativo', 'Em desenvolvimento', 'Em planejamento'] as const;
export type ProjectCategory = (typeof projectCategories)[number];
export type ProjectStatus = (typeof projectStatuses)[number];
export type Project = { id: string; slug: string; name: string; categories: ProjectCategory[]; status: ProjectStatus; featured?: boolean; shortDescription: string; description: string; coverImage?: string; accentColor: string; url?: string; cta?: string; tags: string[]; };
export const projects: Project[] = [
  { id: 'crm', slug: 'crm', name: 'Forja CRM', categories: ['Tecnologia'], status: 'Em desenvolvimento', featured: true, shortDescription: 'Uma ferramenta comercial para organizar relações e trabalho com clareza.', description: 'O Forja CRM é o projeto prioritário em desenvolvimento. Uma ferramenta pensada para transformar contatos, rotinas e contexto comercial em trabalho mais claro.', accentColor: '#c8f34a', tags: ['Software', 'Produto', 'Relações'] },
  { id: 'cafe-com-mattoso', slug: 'cafe-com-mattoso', name: 'Café com Mattoso', categories: ['Conteúdo'], status: 'Ativo', shortDescription: 'Conversas, vídeos, textos e reflexões sobre pessoas, trabalho e escolhas.', description: 'Um projeto de conteúdo da A Forja que reúne conversas, episódios, histórias e ideias que mantêm as pessoas no centro.', coverImage: publicAsset('images/marcelo-cafe-hero.jpg'), accentColor: '#d9a342', url: '/cafe-com-mattoso', cta: 'Visitar o Café', tags: ['Vídeos', 'Textos', 'Palestras'] },
  { id: 'ascensao-heroica', slug: 'ascensao-heroica', name: 'Ascensão Heróica', categories: ['Tecnologia', 'Entretenimento'], status: 'Em desenvolvimento', shortDescription: 'Jogo e universo narrativo de heróis, escolhas e histórias em expansão.', description: 'Um espaço para explorar personagens, sistemas e as consequências de cada escolha.', accentColor: '#a98bff', tags: ['Jogo', 'Narrativa', 'HQs'] },
  { id: 'cronicas-cafe-pao-milagre', slug: 'cronicas-cafe-pao-milagre', name: 'Crônicas do Café, Pão e Milagre', categories: ['Conteúdo', 'Entretenimento'], status: 'Ativo', shortDescription: 'Série literária sobre encontros, quedas e os milagres que cabem numa mesa.', description: 'Uma série de livros publicada que amplia as conversas do Café por meio de ficção, personagens e histórias.', accentColor: '#e6b578', url: '/historias', cta: 'Conhecer os livros', tags: ['Livros', 'Série literária'] },
  { id: 'athos', slug: 'athos', name: 'Athos', categories: ['Tecnologia', 'Entretenimento'], status: 'Em planejamento', shortDescription: 'Um mundo para explorar, imaginar e construir.', description: 'Uma frente autoral em planejamento, pensada como um universo aberto à exploração, criação e participação.', accentColor: '#66b6c5', tags: ['Jogo', 'Universo'] },
  { id: 'thronus', slug: 'thronus', name: 'Thronus', categories: ['Entretenimento'], status: 'Em planejamento', shortDescription: 'Um universo de fantasia, escolhas e consequências.', description: 'Um universo em planejamento que poderá receber histórias, jogos e outras experiências.', accentColor: '#cb7c56', tags: ['Universo', 'Histórias'] },
];
export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
